    CREATE TABLE notificacao_da_consulta (
        id_notificacao NUMBER PRIMARY KEY,
        id_consulta NUMBER,             
        mensagem VARCHAR2(255),         
        data_criacao TIMESTAMP            
    );
-------------------------------------------------------------------------------
CREATE TABLE historico_comparecimento (
    id_registro NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    id_aluno NUMBER NOT NULL, 
    data_comparecimento DATE NOT NULL,
    hora_comparecimento TIMESTAMP, 
    status VARCHAR2(50), 
    observacoes VARCHAR2(255)
);

------------------------------------------------------------------------------

CREATE TABLE PACIENTE (
    ID_PACIENTE NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    CPF VARCHAR2(11) NOT NULL UNIQUE,
    DATA_NASCIMENTO DATE,
    EMAIL VARCHAR2(100)
);

-------------------------------------------------------------------------------

CREATE TABLE PROFISSIONAL_SAUDE (
    ID_PROFISSIONAL NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    ESPECIALIDADE VARCHAR2(100) NOT NULL,
    REGISTRO_PROFISSIONAL VARCHAR2(20) UNIQUE NOT NULL,
    TELEFONE VARCHAR2(20),
    EMAIL VARCHAR2(100),
    ENDERECO VARCHAR2(255)
);
------------------------------------------------------------------------------
CREATE TABLE CONSULTA (
    ID_CONSULTA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    DATA_CONSULTA DATE NOT NULL,                              
    ID_PACIENTE NUMBER,                                      
    ID_MEDICO NUMBER,                                        
    OBSERVACOES VARCHAR2(4000)
);
--------------------------------------------------------------------------------

CREATE TABLE agendamento (
    id_agendamento NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    data_hora TIMESTAMP NOT NULL,
    descricao VARCHAR2(255),
    id_paciente NUMBER
);
--------------------------------------------------------------------------------

CREATE TABLE NOTIFICACAO_CONSULTA_MEDICA (
    ID_NOTIFICACAO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_CONSULTA NUMBER NOT NULL,
    ID_PACIENTE NUMBER NOT NULL,
    MENSAGEM VARCHAR2(4000),
    DATA_NOTIFICACAO TIMESTAMP,
    STATUS VARCHAR2(50)
);

---------------------------------------------------------------------------------















